package:
  name: oitg
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py38_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  script: python setup.py install

requirements:
  build:
    - python >=3.8
    - setuptools
    - statsmodels
  run:
    - python >=3.8
    - numpy
    - h5py
    - statsmodels
    - scipy
    # Version 5.2.9 of Conda's xz package is broken (so that lzma from Python's standard
    # library fails to import), but does not seem to have been unpublished/…, so
    # manually disallow it for now
    # (https://github.com/conda-forge/xz-feedstock/issues/31).
    - xz <=5.2.8,>5.2.9
